markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : unsure.org
production_url : http://unsure.org
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Carlos Alexandro Becker."
disqus_shortname: unsureorg
analytics: UA-32899481-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : matthew finlayson
  github : savagegus
  twitter : savagegus
